# Prometheus configuration for Intent Orchestration Platform monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Intent Orchestration Platform main application
  - job_name: 'intent-platform'
    static_configs:
      - targets: ['intent-platform:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # CAMARA Mock APIs
  - job_name: 'camara-apis'
    static_configs:
      - targets: ['intent-platform:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Redis metrics (if using redis exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL metrics (if using postgres exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Nginx metrics (if using nginx exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Custom recording rules for Intent Orchestration Platform
rule_files:
  - "/etc/prometheus/intent_platform_rules.yml"